### PR TITLE
Updated Blogs and Made New Posts

### PR DESCRIPTION
**Pull request by HeartSongInPurple**

### CODE REVIEW

**Comment by lsblakk** [comment]
Carmen - before you make any further pull requests, please be sure to update your repo with the main repo's code because this is the third time there's been merge conflicts.  

git pull ascend

commit that merge and push to your repo, then make more changes.

**Comment by HeartSongInPurple** [comment]
Thanks for the tip; it was unclear why I was seeing merge conflicts.

**Comment by HeartSongInPurple** [comment]
I typed in "git pull ascend gh-pages" and got a bunch of new files.

I then tried to type "git commit" but it told me there was nothing to
commit.

What did you mean by "commit that merge"?

After trying the "git commit", I typed "git push origin" and it updated my
repo.

I'm guessing now I can make more changes.

**Comment by lsblakk** [comment]
That’s correct - your repo is now up to date with the main one.

**Pull request merged**
